version: '3.8'

services:

  bot:

    container_name: ${CONTAINER_NAME}-bot
    restart: "unless-stopped"
    build: .
    depends_on:
      - postgres
      - redis
    env_file: 
      - .env

  postgres:

    image: postgres:14-alpine
    container_name: ${CONTAINER_NAME}-postgres
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql/data

  redis:

    image: redis:6.2.5-alpine
    container_name: ${CONTAINER_NAME}-redis
    restart: "on-failure"
    volumes:
      - ${VOLUMES_DIR}/redis:/data
    command: redis-server --stop-writes-on-bgsave-error no
    depends_on:
      - redis-overcommit

  redis-overcommit:

    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    container_name: ${CONTAINER_NAME}-redis-overcommit
    restart: "no"
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm

